/*Config
    RetornaLista
    Retorno
        -ArquivoUploadEntidade
    Parametros
        -OID_CONTRIBUINTE:decimal
*/

select DISTINCT EFD_ARQUIVO_UPLOAD.*,
                EFD_R1070.IND_AMBIENTE_ENVIO,
				EFD_R1070.OID_USUARIO_ENVIO 
from EFD_ARQUIVO_UPLOAD
INNER JOIN EFD_USUARIO_CONTRIBUINTE ON EFD_ARQUIVO_UPLOAD.OID_USUARIO_CONTRIBUINTE = EFD_USUARIO_CONTRIBUINTE.OID_USUARIO_CONTRIBUINTE
INNER JOIN EFD_R1070 ON EFD_ARQUIVO_UPLOAD.OID_ARQUIVO_UPLOAD = EFD_R1070.OID_ARQUIVO_UPLOAD
WHERE EFD_USUARIO_CONTRIBUINTE.OID_CONTRIBUINTE = 10091
  AND IND_SITUACAO_PROCESSAMENTO <> 'ENV'