/*Config
    RetornaLista
    Retorno
        -ArquivoUploadEntidade
    Parametros
        -OID_CONTRIBUINTE:decimal
*/

select DISTINCT EFD_ARQUIVO_UPLOAD.*,
                EFD_R2010.IND_AMBIENTE_ENVIO,
				EFD_R2010.OID_USUARIO_ENVIO ,
				EFD_R2010.IND_SITUACAO_PROCESSAMENTO
from EFD_ARQUIVO_UPLOAD
INNER JOIN EFD_USUARIO_CONTRIBUINTE ON EFD_ARQUIVO_UPLOAD.OID_USUARIO_CONTRIBUINTE = EFD_USUARIO_CONTRIBUINTE.OID_USUARIO_CONTRIBUINTE
INNER JOIN EFD_R2010 ON EFD_ARQUIVO_UPLOAD.OID_ARQUIVO_UPLOAD = EFD_R2010.OID_ARQUIVO_UPLOAD
WHERE EFD_USUARIO_CONTRIBUINTE.OID_CONTRIBUINTE = @OID_CONTRIBUINTE
  AND IND_SITUACAO_PROCESSAMENTO <> 'ENV'