/*Config
    RetornaLista
    Retorno
        -ContribuinteEnvioEntidade
    Parametros
        -OID_CONTRIBUINTE:decimal
*/

SELECT EFD_CONTRIBUINTE_ENVIO.*,
    EFD_ARQUIVO_UPLOAD.DTA_UPLOAD,
    EFD_ARQUIVO_UPLOAD.IND_STATUS
FROM EFD_CONTRIBUINTE_ENVIO
INNER JOIN EFD_ARQUIVO_UPLOAD ON EFD_ARQUIVO_UPLOAD.OID_ARQUIVO_UPLOAD = EFD_CONTRIBUINTE_ENVIO.OID_ARQUIVO_UPLOAD
WHERE OID_CONTRIBUINTE = @OID_CONTRIBUINTE