/*Config
    Retorno
        -ContribuinteEntidade
    Parametros
        -COD_CNPJ_CPF:string
        -OID_USUARIO:decimal
*/

SELECT *
FROM EFD_CONTRIBUINTE
INNER JOIN EFD_USUARIO_CONTRIBUINTE ON EFD_USUARIO_CONTRIBUINTE.OID_CONTRIBUINTE = EFD_CONTRIBUINTE.OID_CONTRIBUINTE
WHERE EFD_CONTRIBUINTE.COD_CNPJ_CPF = @COD_CNPJ_CPF
  AND EFD_USUARIO_CONTRIBUINTE.OID_USUARIO = @OID_USUARIO