/*Config
	RetornaLista
    Retorno
        -R2010Entidade
    Parametros
        -OID_CONTRIBUINTE:decimal
		-MES_ENVIO:decimal
		-ANO_ENVIO:decimal
		-IND_SITUACAO_PROCESSAMENTO:string
*/

SELECT EFD_R2010.* 
FROM EFD_R2010
WHERE EFD_R2010.OID_CONTRIBUINTE = @OID_CONTRIBUINTE
  AND EFD_R2010.DTA_ENVIO = ( SELECT MAX(A.DTA_ENVIO)
							  FROM EFD_R2010 AS A 
							  WHERE ( A.OID_CONTRIBUINTE = @OID_CONTRIBUINTE )
							    AND (MONTH(A.DTA_ENVIO) = @MES_ENVIO)
								AND (YEAR(A.DTA_ENVIO) = @ANO_ENVIO )
								AND (A.NUM_RECIBO_ENVIO <> NULL))
  AND IND_SITUACAO_PROCESSAMENTO = @IND_SITUACAO_PROCESSAMENTO
ORDER BY EFD_R2010.DTA_APURACAO, EFD_R2010.COD_CNPJ_PRESTADOR, EFD_R2010.COD_SERIE_NF, EFD_R2010.NUM_DOCUMENTO_NF, EFD_R2010.DTA_EMISSAO_NF