/*Config
	RetornaLista
    Retorno
        -R2010Entidade
    Parametros
        -OID_CONTRIBUINTE:decimal
		-DTA_INICIO:DateTime
		-DTA_FIM:DateTime
		-IND_SITUACAO_PROCESSAMENTO:string
*/

SELECT * 
FROM EFD_R2010
WHERE OID_CONTRIBUINTE = @OID_CONTRIBUINTE
  AND DTA_APURACAO >= @DTA_INICIO
  AND DTA_APURACAO <= @DTA_FIM
  AND IND_SITUACAO_PROCESSAMENTO = @IND_SITUACAO_PROCESSAMENTO
ORDER BY DTA_APURACAO, COD_CNPJ_PRESTADOR, COD_SERIE_NF, NUM_DOCUMENTO_NF, DTA_EMISSAO_NF