/*Config
	RetornaLista
    Retorno
        -DateTime
    Parametros
        -OID_CONTRIBUINTE:decimal
*/

SELECT DTA_APURACAO
FROM EFD_R2010
WHERE OID_CONTRIBUINTE = @OID_CONTRIBUINTE
  AND IND_SITUACAO_PROCESSAMENTO = 'ENV'
ORDER BY DTA_APURACAO